# Generated by Django 4.1.7 on 2024-01-30 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ride_sharing_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="driver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides_as_driver",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(default="requested", max_length=20),
        ),
    ]
