# Generated by Django 4.1.7 on 2024-01-31 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ride_sharing_app", "0009_userprofile_confirm_password_userprofile_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile", old_name="user", new_name="username",
        ),
    ]
