# Generated by Django 4.1.7 on 2024-01-31 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ride_sharing_app", "0010_rename_user_userprofile_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile", old_name="username", new_name="user",
        ),
    ]
