# Generated by Django 4.1.7 on 2024-01-31 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ride_sharing_app", "0011_rename_username_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="ride", name="driver",),
        migrations.RemoveField(model_name="ride", name="rider",),
        migrations.DeleteModel(name="UserProfile",),
        migrations.DeleteModel(name="Ride",),
    ]
