# Generated by Django 4.1.7 on 2024-02-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ride_sharing_app", "0013_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="current_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="current_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
