# Generated by Django 4.1.7 on 2024-02-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ride_sharing_app", "0014_ride_current_latitude_ride_current_longitude"),
    ]

    operations = [
        migrations.RemoveField(model_name="ride", name="current_latitude",),
        migrations.RemoveField(model_name="ride", name="current_longitude",),
        migrations.AddField(
            model_name="ride",
            name="current_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
