# Generated by Django 4.1.7 on 2024-02-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ride_sharing_app", "0015_remove_ride_current_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="current_location",
            field=models.TextField(blank=True, null=True),
        ),
    ]
