# Generated by Django 4.1.7 on 2024-02-01 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ride_sharing_app", "0019_userprofile_is_available_userprofile_is_driver"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="is_available",),
        migrations.RemoveField(model_name="userprofile", name="is_driver",),
    ]
